
version: "3.3"
services:

    app:
      image: jackcharles13/tem:latest
      build: ./app
      container_name: application
      ports:
        - target: 5000
        published: 80
        protocol: 5000
